# Docker compose version
version: "3.7"

services:
  springapp:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/DevOpsBootCamp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8084:8084"
    volumes:
      - .:/app
    depends_on:
      - PostgreSQL
    networks:
      - spring
  PostgreSQL:
    container_name: database
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=DevOpsBootCamp
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - spring
  pgadmin:
    container_name: databaseAdmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - PostgreSQL
    networks:
      - spring
volumes:
  postgres:
  pgadmin-data:
networks:
  spring:
    driver: bridge
